global:
    scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['localhost:9090', 'demo.robustperception.io:9090']
  - job_name: node
    target_groups:
      - targets: ['demo.robustperception.io:9100']
  - job_name: dummy
    file_sd_configs:
      - names:
        - file_sd_config.json
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex:         '.*,(prod|dev),.*'
        target_label:  'env'
        replacement:   '$1'
rule_files:
 - prometheus.rules