global:
    scrape_interval: 10s
scrape_confixxxxgs:
  - job_name: 'prometheus'
    target_groups:
      - targets: ['localhost:9090', 'demo.robustperception.io:9090']
  - job_name: node
    target_groups:
      - targets: ['demo.robustperception.io:9100']
  - job_name: dummy
    file_sd_configs:
      - names:
        - file_sd_config.json
rule_files:
 - prometheus.rules